name: Trigger auto deployment for aca-front-demo-fc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ Dev-NewFeature ]
    paths:
    - 'samples/aspnetapp/**'
    - '.github/workflows/aca-front-demo-fc-AutoDeployTrigger-7f5d44c1-6883-40f0-a092-31174b5feafa.yml'

  # Allow mannually trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ACAFRONTDEMOFC_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/samples/aspnetapp 
          registryUrl: acrjskubeeducwe.azurecr.io
          registryUsername: ${{ secrets.ACAFRONTDEMOFC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAFRONTDEMOFC_REGISTRY_PASSWORD }}
          containerAppName: aca-front-demo-fc
          resourceGroup: rg-demo-aca-prd-fc
          imageToBuild: acrjskubeeducwe.azurecr.io/aca-front-demo-fc:${{ github.sha }}
          dockerfilePath: Dockerfile

     

